name: Workflow Triggered by Repository Dispatch

on:
  repository_dispatch:
    types:
      - triggering_another_repo

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - run: echo "Trigger a workflow with another repo's workflow"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  
